import { Tile } from "./types"

export const board: Tile[] = [
  { type: "start" },
  { type: "property", propertyId: "p1" },
  { type: "treasure" },
  { type: "property", propertyId: "p2" },
  { type: "incomeTax" },
  { type: "property", propertyId: "p3" },
  { type: "property", propertyId: "p4" },
  { type: "chance" },
  { type: "property", propertyId: "p5" },
  { type: "property", propertyId: "p6" },
  { type: "jail" },
  { type: "property", propertyId: "p7" },
  { type: "property", propertyId: "p8" },
  { type: "property", propertyId: "p9" },
  { type: "property", propertyId: "p10" },
  { type: "property", propertyId: "p11" },
  { type: "property", propertyId: "p12" },
  { type: "treasure" },
  { type: "property", propertyId: "p13" },
  { type: "property", propertyId: "p14" },
  { type: "vacation" },
  { type: "property", propertyId: "p15" },
  { type: "chance" },
  { type: "property", propertyId: "p16" },
  { type: "property", propertyId: "p17" },
  { type: "property", propertyId: "p18" },
  { type: "property", propertyId: "p19" },
  { type: "property", propertyId: "p20" },
  { type: "property", propertyId: "p21" },
  { type: "property", propertyId: "p22" },
  { type: "goToJail" },
  { type: "property", propertyId: "p23" },
  { type: "property", propertyId: "p24" },
  { type: "treasure" },
  { type: "property", propertyId: "p25" },
  { type: "property", propertyId: "p26" },
  { type: "chance" },
  { type: "property", propertyId: "p27" },
  { type: "cashTax" },
  { type: "property", propertyId: "p28" }
]
